//  改背景

// body
const body = document.body

// 畫面背景
const background_color = document.querySelectorAll('.td_content')

// 時鐘黑邊框
const clock_side = document.querySelectorAll(
	`#tr_clock_2 .td_clock_11,
  #tr_clock_2 .td_clock_12,
  #tr_clock_2 .td_clock_19,
  #tr_clock_2 .td_clock_20,
  #tr_clock_3 .td_clock_7,
  #tr_clock_3 .td_clock_8,
  #tr_clock_3 .td_clock_9,
  #tr_clock_3 .td_clock_10,
  #tr_clock_3 .td_clock_11,
  #tr_clock_3 .td_clock_12,
  #tr_clock_3 .td_clock_13,
  #tr_clock_3 .td_clock_18,
  #tr_clock_3 .td_clock_19,
  #tr_clock_3 .td_clock_20,
  #tr_clock_3 .td_clock_21,
  #tr_clock_3 .td_clock_22,
  #tr_clock_3 .td_clock_23,
  #tr_clock_3 .td_clock_24,
  #tr_clock_4 .td_clock_7,
  #tr_clock_4 .td_clock_8,
  #tr_clock_4 .td_clock_9,
  #tr_clock_4 .td_clock_10,
  #tr_clock_4 .td_clock_11,
  #tr_clock_4 .td_clock_12,
  #tr_clock_4 .td_clock_13,
  #tr_clock_4 .td_clock_17,
  #tr_clock_4 .td_clock_18,
  #tr_clock_4 .td_clock_19,
  #tr_clock_4 .td_clock_20,
  #tr_clock_4 .td_clock_21,
  #tr_clock_4 .td_clock_22,
  #tr_clock_4 .td_clock_23,
  #tr_clock_4 .td_clock_24,
  #tr_clock_5 .td_clock_5,
  #tr_clock_5 .td_clock_6,
  #tr_clock_5 .td_clock_25,
  #tr_clock_5 .td_clock_26,
  #tr_clock_6 .td_clock_5,
  #tr_clock_6 .td_clock_6,
  #tr_clock_6 .td_clock_25,
  #tr_clock_6 .td_clock_26,
  #tr_clock_7 .td_clock_4,
  #tr_clock_7 .td_clock_27,
  #tr_clock_8 .td_clock_2,
  #tr_clock_8 .td_clock_3,
  #tr_clock_8 .td_clock_28,
  #tr_clock_8 .td_clock_29,
  #tr_clock_9 .td_clock_2,
  #tr_clock_9 .td_clock_3,
  #tr_clock_9 .td_clock_28,
  #tr_clock_9 .td_clock_29,
  #tr_clock_10 .td_clock_2,
  #tr_clock_10 .td_clock_3,
  #tr_clock_10 .td_clock_28,
  #tr_clock_10 .td_clock_29,
  #tr_clock_11 .td_clock_2,
  #tr_clock_11 .td_clock_3,
  #tr_clock_11 .td_clock_28,
  #tr_clock_11 .td_clock_29,
  #tr_clock_12 .td_clock_2,
  #tr_clock_12 .td_clock_3,
  #tr_clock_12 .td_clock_28,
  #tr_clock_12 .td_clock_29,
  #tr_clock_13 .td_clock_2,
  #tr_clock_13 .td_clock_3,
  #tr_clock_13 .td_clock_28,
  #tr_clock_13 .td_clock_29,
  #tr_clock_14 .td_clock_2,
  #tr_clock_14 .td_clock_3,
  #tr_clock_14 .td_clock_28,
  #tr_clock_14 .td_clock_29,
  #tr_clock_15 .td_clock_2,
  #tr_clock_15 .td_clock_3,
  #tr_clock_15 .td_clock_28,
  #tr_clock_15 .td_clock_29,
  #tr_clock_16 .td_clock_2,
  #tr_clock_16 .td_clock_3,
  #tr_clock_16 .td_clock_28,
  #tr_clock_16 .td_clock_29,
  #tr_clock_17 .td_clock_2,
  #tr_clock_17 .td_clock_3,
  #tr_clock_17 .td_clock_28,
  #tr_clock_17 .td_clock_29,
  #tr_clock_18 .td_clock_2,
  #tr_clock_18 .td_clock_3,
  #tr_clock_18 .td_clock_28,
  #tr_clock_18 .td_clock_29,
  #tr_clock_19 .td_clock_2,
  #tr_clock_19 .td_clock_3,
  #tr_clock_19 .td_clock_28,
  #tr_clock_19 .td_clock_29,
  #tr_clock_20 .td_clock_2,
  #tr_clock_20 .td_clock_3,
  #tr_clock_20 .td_clock_28,
  #tr_clock_20 .td_clock_29,
  #tr_clock_21 .td_clock_2,
  #tr_clock_21 .td_clock_3,
  #tr_clock_21 .td_clock_28,
  #tr_clock_21 .td_clock_29,
  #tr_clock_22 .td_clock_2,
  #tr_clock_22 .td_clock_3,
  #tr_clock_22 .td_clock_28,
  #tr_clock_22 .td_clock_29,
  #tr_clock_23 .td_clock_2,
  #tr_clock_23 .td_clock_3,
  #tr_clock_23 .td_clock_28,
  #tr_clock_23 .td_clock_29,
  #tr_clock_24 .td_clock_2,
  #tr_clock_24 .td_clock_3,
  #tr_clock_24 .td_clock_28,
  #tr_clock_24 .td_clock_29,
  #tr_clock_25 .td_clock_4,
  #tr_clock_25 .td_clock_27,
  #tr_clock_26 .td_clock_4,
  #tr_clock_26 .td_clock_27,
  #tr_clock_27 .td_clock_5,
  #tr_clock_27 .td_clock_6,
  #tr_clock_27 .td_clock_25,
  #tr_clock_27 .td_clock_26,
  #tr_clock_28 .td_clock_7,
  #tr_clock_28 .td_clock_8,
  #tr_clock_28 .td_clock_9,
  #tr_clock_28 .td_clock_10,
  #tr_clock_28 .td_clock_11,
  #tr_clock_28 .td_clock_12,
  #tr_clock_28 .td_clock_13,
  #tr_clock_28 .td_clock_14,
  #tr_clock_28 .td_clock_15,
  #tr_clock_28 .td_clock_16,
  #tr_clock_28 .td_clock_17,
  #tr_clock_28 .td_clock_18,
  #tr_clock_28 .td_clock_19,
  #tr_clock_28 .td_clock_20,
  #tr_clock_28 .td_clock_21,
  #tr_clock_28 .td_clock_22,
  #tr_clock_28 .td_clock_23,
  #tr_clock_28 .td_clock_24,
  #tr_clock_29 .td_clock_7,
  #tr_clock_29 .td_clock_8,
  #tr_clock_29 .td_clock_9,
  #tr_clock_29 .td_clock_10,
  #tr_clock_29 .td_clock_11,
  #tr_clock_29 .td_clock_12,
  #tr_clock_29 .td_clock_13,
  #tr_clock_29 .td_clock_14,
  #tr_clock_29 .td_clock_15,
  #tr_clock_29 .td_clock_16,
  #tr_clock_29 .td_clock_17,
  #tr_clock_29 .td_clock_18,
  #tr_clock_29 .td_clock_19,
  #tr_clock_29 .td_clock_20,
  #tr_clock_29 .td_clock_21,
  #tr_clock_29 .td_clock_22,
  #tr_clock_29 .td_clock_23,
  #tr_clock_29 .td_clock_24`
)

//  時鐘本體紅色
const clock_red = document.querySelectorAll(
	`#tr_clock_2 .td_clock_13,
  #tr_clock_2 .td_clock_14,
  #tr_clock_2 .td_clock_15,
  #tr_clock_2 .td_clock_18,
  #tr_clock_2 .td_clock_19,
  #tr_clock_3 .td_clock_14,
  #tr_clock_3 .td_clock_15,
  #tr_clock_4 .td_clock_14,
  #tr_clock_4 .td_clock_15,
  #tr_clock_4 .td_clock_16,
  #tr_clock_5 .td_clock_7,
  #tr_clock_5 .td_clock_8,
  #tr_clock_5 .td_clock_9,
  #tr_clock_5 .td_clock_10,
  #tr_clock_5 .td_clock_11,
  #tr_clock_5 .td_clock_12,
  #tr_clock_5 .td_clock_13,
  #tr_clock_5 .td_clock_14,
  #tr_clock_5 .td_clock_15,
  #tr_clock_5 .td_clock_16,
  #tr_clock_5 .td_clock_17,
  #tr_clock_5 .td_clock_18,
  #tr_clock_5 .td_clock_19,
  #tr_clock_5 .td_clock_20,
  #tr_clock_5 .td_clock_21,
  #tr_clock_5 .td_clock_22,
  #tr_clock_5 .td_clock_23,
  #tr_clock_5 .td_clock_24,
  #tr_clock_6 .td_clock_7,
  #tr_clock_6 .td_clock_8,
  #tr_clock_6 .td_clock_9,
  #tr_clock_6 .td_clock_24,
  #tr_clock_6 .td_clock_25,
  #tr_clock_6 .td_clock_26,
  #tr_clock_7 .td_clock_5,
  #tr_clock_7 .td_clock_6,
  #tr_clock_7 .td_clock_8,
  #tr_clock_7 .td_clock_9,
  #tr_clock_7 .td_clock_24,
  #tr_clock_7 .td_clock_25,
  #tr_clock_7 .td_clock_26,
  #tr_clock_8 .td_clock_4,
  #tr_clock_8 .td_clock_7,
  #tr_clock_8 .td_clock_25,
  #tr_clock_8 .td_clock_26,
  #tr_clock_8 .td_clock_27,
  #tr_clock_9 .td_clock_4,
  #tr_clock_9 .td_clock_7,
  #tr_clock_9 .td_clock_25,
  #tr_clock_9 .td_clock_26,
  #tr_clock_9 .td_clock_27,
  #tr_clock_10 .td_clock_5,
  #tr_clock_10 .td_clock_6,
  #tr_clock_10 .td_clock_27,
  #tr_clock_11 .td_clock_5,
  #tr_clock_11 .td_clock_6,
  #tr_clock_11 .td_clock_27,
  #tr_clock_12 .td_clock_5,
  #tr_clock_12 .td_clock_6,
  #tr_clock_12 .td_clock_27,
  #tr_clock_13 .td_clock_5,
  #tr_clock_13 .td_clock_6,
  #tr_clock_13 .td_clock_27,
  #tr_clock_14 .td_clock_4,
  #tr_clock_14 .td_clock_5,
  #tr_clock_14 .td_clock_6,
  #tr_clock_14 .td_clock_27,
  #tr_clock_15 .td_clock_4,
  #tr_clock_15 .td_clock_5,
  #tr_clock_15 .td_clock_6,
  #tr_clock_15 .td_clock_27,
  #tr_clock_16 .td_clock_4,
  #tr_clock_16 .td_clock_5,
  #tr_clock_16 .td_clock_6,
  #tr_clock_16 .td_clock_27,
  #tr_clock_17 .td_clock_4,
  #tr_clock_17 .td_clock_5,
  #tr_clock_17 .td_clock_6,
  #tr_clock_17 .td_clock_27,
  #tr_clock_18 .td_clock_4,
  #tr_clock_18 .td_clock_5,
  #tr_clock_18 .td_clock_6,
  #tr_clock_18 .td_clock_27,
  #tr_clock_19 .td_clock_4,
  #tr_clock_19 .td_clock_5,
  #tr_clock_19 .td_clock_6,
  #tr_clock_19 .td_clock_27,
  #tr_clock_20 .td_clock_4,
  #tr_clock_20 .td_clock_5,
  #tr_clock_20 .td_clock_6,
  #tr_clock_20 .td_clock_27,
  #tr_clock_21 .td_clock_4,
  #tr_clock_21 .td_clock_5,
  #tr_clock_21 .td_clock_6,
  #tr_clock_21 .td_clock_27,
  #tr_clock_22 .td_clock_4,
  #tr_clock_22 .td_clock_5,
  #tr_clock_22 .td_clock_6,
  #tr_clock_22 .td_clock_27,
  #tr_clock_23 .td_clock_4,
  #tr_clock_23 .td_clock_5,
  #tr_clock_23 .td_clock_6,
  #tr_clock_23 .td_clock_27,
  #tr_clock_24 .td_clock_4,
  #tr_clock_24 .td_clock_5,
  #tr_clock_24 .td_clock_6,
  #tr_clock_24 .td_clock_7,
  #tr_clock_24 .td_clock_25,
  #tr_clock_24 .td_clock_26,
  #tr_clock_24 .td_clock_27,
  #tr_clock_24 .td_clock_4,
  #tr_clock_24 .td_clock_5,
  #tr_clock_24 .td_clock_6,
  #tr_clock_24 .td_clock_7,
  #tr_clock_24 .td_clock_26,
  #tr_clock_25 .td_clock_5,
  #tr_clock_25 .td_clock_6,
  #tr_clock_25 .td_clock_7,
  #tr_clock_25 .td_clock_8,
  #tr_clock_25 .td_clock_9,
  #tr_clock_25 .td_clock_24,
  #tr_clock_25 .td_clock_25,
  #tr_clock_25 .td_clock_26,
  #tr_clock_26 .td_clock_5,
  #tr_clock_26 .td_clock_6,
  #tr_clock_26 .td_clock_7,
  #tr_clock_26 .td_clock_8,
  #tr_clock_26 .td_clock_9,
  #tr_clock_26 .td_clock_24,
  #tr_clock_26 .td_clock_25,
  #tr_clock_26 .td_clock_26,
  #tr_clock_27 .td_clock_7,
  #tr_clock_27 .td_clock_8,
  #tr_clock_27 .td_clock_9,
  #tr_clock_27 .td_clock_10,
  #tr_clock_27 .td_clock_11,
  #tr_clock_27 .td_clock_12,
  #tr_clock_27 .td_clock_13,
  #tr_clock_27 .td_clock_14,
  #tr_clock_27 .td_clock_15,
  #tr_clock_27 .td_clock_16,
  #tr_clock_27 .td_clock_17,
  #tr_clock_27 .td_clock_18,
  #tr_clock_27 .td_clock_19,
  #tr_clock_27 .td_clock_20,
  #tr_clock_27 .td_clock_21,
  #tr_clock_27 .td_clock_22,
  #tr_clock_27 .td_clock_23,
  #tr_clock_27 .td_clock_24`
)

//  時鐘反光黃
const clock_yellow = document.querySelectorAll(`
#tr_clock_2 .td_clock_16,
#tr_clock_2 .td_clock_17,
#tr_clock_3 .td_clock_16,
#tr_clock_3 .td_clock_17,
#tr_clock_7 .td_clock_7,
#tr_clock_8 .td_clock_5,
#tr_clock_8 .td_clock_6,
#tr_clock_9 .td_clock_5,
#tr_clock_9 .td_clock_6,
#tr_clock_10 .td_clock_4,
#tr_clock_11 .td_clock_4,
#tr_clock_12 .td_clock_4,
#tr_clock_13 .td_clock_4`)

//  時鐘中間白
const clock_white = document.querySelectorAll(
	`#tr_clock_8 .td_clock_10,
  #tr_clock_8 .td_clock_13,
  #tr_clock_8 .td_clock_14,
  #tr_clock_8 .td_clock_15,
  #tr_clock_8 .td_clock_17,
  #tr_clock_8 .td_clock_18,
  #tr_clock_8 .td_clock_19,
  #tr_clock_8 .td_clock_22,
  #tr_clock_9 .td_clock_10,
  #tr_clock_9 .td_clock_13,
  #tr_clock_9 .td_clock_14,
  #tr_clock_9 .td_clock_15,
  #tr_clock_9 .td_clock_16,
  #tr_clock_9 .td_clock_17,
  #tr_clock_9 .td_clock_18,
  #tr_clock_9 .td_clock_19,
  #tr_clock_9 .td_clock_22,
  #tr_clock_10 .td_clock_8,
  #tr_clock_10 .td_clock_9,
  #tr_clock_10 .td_clock_10,
  #tr_clock_10 .td_clock_11,
  #tr_clock_10 .td_clock_12,
  #tr_clock_10 .td_clock_13,
  #tr_clock_10 .td_clock_14,
  #tr_clock_10 .td_clock_15,
  #tr_clock_10 .td_clock_16,
  #tr_clock_10 .td_clock_17,
  #tr_clock_10 .td_clock_18,
  #tr_clock_10 .td_clock_19,
  #tr_clock_10 .td_clock_20,
  #tr_clock_10 .td_clock_21,
  #tr_clock_10 .td_clock_22,
  #tr_clock_10 .td_clock_23,
  #tr_clock_10 .td_clock_24,
  #tr_clock_11 .td_clock_10,
  #tr_clock_11 .td_clock_11,
  #tr_clock_11 .td_clock_12,
  #tr_clock_11 .td_clock_13,
  #tr_clock_11 .td_clock_14,
  #tr_clock_11 .td_clock_15,
  #tr_clock_11 .td_clock_16,
  #tr_clock_11 .td_clock_17,
  #tr_clock_11 .td_clock_18,
  #tr_clock_11 .td_clock_19,
  #tr_clock_11 .td_clock_20,
  #tr_clock_11 .td_clock_21,
  #tr_clock_11 .td_clock_22,
  #tr_clock_12 .td_clock_10,
  #tr_clock_12 .td_clock_11,
  #tr_clock_12 .td_clock_12,
  #tr_clock_12 .td_clock_13,
  #tr_clock_12 .td_clock_14,
  #tr_clock_12 .td_clock_15,
  #tr_clock_12 .td_clock_16,
  #tr_clock_12 .td_clock_17,
  #tr_clock_12 .td_clock_18,
  #tr_clock_12 .td_clock_19,
  #tr_clock_12 .td_clock_20,
  #tr_clock_12 .td_clock_21,
  #tr_clock_12 .td_clock_22,
  #tr_clock_13 .td_clock_8,
  #tr_clock_13 .td_clock_9,
  #tr_clock_13 .td_clock_10,
  #tr_clock_13 .td_clock_11,
  #tr_clock_13 .td_clock_12,
  #tr_clock_13 .td_clock_13,
  #tr_clock_13 .td_clock_14,
  #tr_clock_13 .td_clock_15,
  #tr_clock_13 .td_clock_16,
  #tr_clock_13 .td_clock_17,
  #tr_clock_13 .td_clock_18,
  #tr_clock_13 .td_clock_19,
  #tr_clock_13 .td_clock_20,
  #tr_clock_13 .td_clock_21,
  #tr_clock_13 .td_clock_22,
  #tr_clock_13 .td_clock_23,
  #tr_clock_13 .td_clock_24,
  #tr_clock_14 .td_clock_8,
  #tr_clock_14 .td_clock_9,
  #tr_clock_14 .td_clock_10,
  #tr_clock_14 .td_clock_11,
  #tr_clock_14 .td_clock_12,
  #tr_clock_14 .td_clock_13,
  #tr_clock_14 .td_clock_14,
  #tr_clock_14 .td_clock_15,
  #tr_clock_14 .td_clock_16,
  #tr_clock_14 .td_clock_17,
  #tr_clock_14 .td_clock_18,
  #tr_clock_14 .td_clock_19,
  #tr_clock_14 .td_clock_20,
  #tr_clock_14 .td_clock_21,
  #tr_clock_14 .td_clock_22,
  #tr_clock_14 .td_clock_23,
  #tr_clock_14 .td_clock_24,
  #tr_clock_15 .td_clock_8,
  #tr_clock_15 .td_clock_9,
  #tr_clock_15 .td_clock_10,
  #tr_clock_15 .td_clock_11,
  #tr_clock_15 .td_clock_12,
  #tr_clock_15 .td_clock_13,
  #tr_clock_15 .td_clock_14,
  #tr_clock_15 .td_clock_15,
  #tr_clock_15 .td_clock_16,
  #tr_clock_15 .td_clock_17,
  #tr_clock_15 .td_clock_18,
  #tr_clock_15 .td_clock_19,
  #tr_clock_15 .td_clock_20,
  #tr_clock_15 .td_clock_21,
  #tr_clock_15 .td_clock_22,
  #tr_clock_15 .td_clock_23,
  #tr_clock_15 .td_clock_24,
  #tr_clock_16 .td_clock_10,
  #tr_clock_16 .td_clock_11,
  #tr_clock_16 .td_clock_12,
  #tr_clock_16 .td_clock_13,
  #tr_clock_16 .td_clock_14,
  #tr_clock_16 .td_clock_15,
  #tr_clock_16 .td_clock_16,
  #tr_clock_16 .td_clock_17,
  #tr_clock_16 .td_clock_18,
  #tr_clock_16 .td_clock_19,
  #tr_clock_16 .td_clock_20,
  #tr_clock_16 .td_clock_21,
  #tr_clock_16 .td_clock_22,
  #tr_clock_17 .td_clock_10,
  #tr_clock_17 .td_clock_11,
  #tr_clock_17 .td_clock_12,
  #tr_clock_17 .td_clock_13,
  #tr_clock_17 .td_clock_14,
  #tr_clock_17 .td_clock_15,
  #tr_clock_17 .td_clock_16,
  #tr_clock_17 .td_clock_17,
  #tr_clock_17 .td_clock_18,
  #tr_clock_17 .td_clock_19,
  #tr_clock_17 .td_clock_20,
  #tr_clock_17 .td_clock_21,
  #tr_clock_17 .td_clock_22,
  #tr_clock_18 .td_clock_8,
  #tr_clock_18 .td_clock_9,
  #tr_clock_18 .td_clock_10,
  #tr_clock_18 .td_clock_11,
  #tr_clock_18 .td_clock_12,
  #tr_clock_18 .td_clock_13,
  #tr_clock_18 .td_clock_14,
  #tr_clock_18 .td_clock_15,
  #tr_clock_18 .td_clock_16,
  #tr_clock_18 .td_clock_17,
  #tr_clock_18 .td_clock_18,
  #tr_clock_18 .td_clock_19,
  #tr_clock_18 .td_clock_20,
  #tr_clock_18 .td_clock_21,
  #tr_clock_18 .td_clock_22,
  #tr_clock_18 .td_clock_23,
  #tr_clock_18 .td_clock_24,
  #tr_clock_19 .td_clock_8,
  #tr_clock_19 .td_clock_9,
  #tr_clock_19 .td_clock_10,
  #tr_clock_19 .td_clock_11,
  #tr_clock_19 .td_clock_12,
  #tr_clock_19 .td_clock_13,
  #tr_clock_19 .td_clock_14,
  #tr_clock_19 .td_clock_15,
  #tr_clock_19 .td_clock_16,
  #tr_clock_19 .td_clock_17,
  #tr_clock_19 .td_clock_18,
  #tr_clock_19 .td_clock_19,
  #tr_clock_19 .td_clock_20,
  #tr_clock_19 .td_clock_21,
  #tr_clock_19 .td_clock_22,
  #tr_clock_19 .td_clock_23,
  #tr_clock_19 .td_clock_24,
  #tr_clock_20 .td_clock_10,
  #tr_clock_20 .td_clock_11,
  #tr_clock_20 .td_clock_12,
  #tr_clock_20 .td_clock_13,
  #tr_clock_20 .td_clock_14,
  #tr_clock_20 .td_clock_15,
  #tr_clock_20 .td_clock_16,
  #tr_clock_20 .td_clock_17,
  #tr_clock_20 .td_clock_18,
  #tr_clock_20 .td_clock_19,
  #tr_clock_20 .td_clock_20,
  #tr_clock_20 .td_clock_21,
  #tr_clock_20 .td_clock_22,
  #tr_clock_21 .td_clock_10,
  #tr_clock_21 .td_clock_11,
  #tr_clock_21 .td_clock_12,
  #tr_clock_21 .td_clock_13,
  #tr_clock_21 .td_clock_14,
  #tr_clock_21 .td_clock_15,
  #tr_clock_21 .td_clock_16,
  #tr_clock_21 .td_clock_17,
  #tr_clock_21 .td_clock_18,
  #tr_clock_21 .td_clock_19,
  #tr_clock_21 .td_clock_20,
  #tr_clock_21 .td_clock_21,
  #tr_clock_21 .td_clock_22,
  #tr_clock_22 .td_clock_8,
  #tr_clock_22 .td_clock_9,
  #tr_clock_22 .td_clock_10,
  #tr_clock_22 .td_clock_11,
  #tr_clock_22 .td_clock_12,
  #tr_clock_22 .td_clock_13,
  #tr_clock_22 .td_clock_14,
  #tr_clock_22 .td_clock_15,
  #tr_clock_22 .td_clock_16,
  #tr_clock_22 .td_clock_17,
  #tr_clock_22 .td_clock_18,
  #tr_clock_22 .td_clock_19,
  #tr_clock_22 .td_clock_20,
  #tr_clock_22 .td_clock_21,
  #tr_clock_22 .td_clock_22,
  #tr_clock_22 .td_clock_23,
  #tr_clock_22 .td_clock_24,
  #tr_clock_23 .td_clock_8,
  #tr_clock_23 .td_clock_9,
  #tr_clock_23 .td_clock_10,
  #tr_clock_23 .td_clock_11,
  #tr_clock_23 .td_clock_12,
  #tr_clock_23 .td_clock_13,
  #tr_clock_23 .td_clock_14,
  #tr_clock_23 .td_clock_15,
  #tr_clock_23 .td_clock_16,
  #tr_clock_23 .td_clock_17,
  #tr_clock_23 .td_clock_18,
  #tr_clock_23 .td_clock_19,
  #tr_clock_23 .td_clock_20,
  #tr_clock_23 .td_clock_21,
  #tr_clock_23 .td_clock_22,
  #tr_clock_23 .td_clock_23,
  #tr_clock_23 .td_clock_24,
  #tr_clock_24 .td_clock_10,
  #tr_clock_24 .td_clock_13,
  #tr_clock_24 .td_clock_14,
  #tr_clock_24 .td_clock_15,
  #tr_clock_24 .td_clock_17,
  #tr_clock_24 .td_clock_18,
  #tr_clock_24 .td_clock_19,
  #tr_clock_24 .td_clock_22,
  #tr_clock_24 .td_clock_23,
  #tr_clock_24 .td_clock_24`
)

// 時鐘綠
const clock_green = document.querySelectorAll(
	`#tr_clock_6 .td_clock_10,
  #tr_clock_6 .td_clock_11,
  #tr_clock_6 .td_clock_12,
  #tr_clock_6 .td_clock_13,
  #tr_clock_6 .td_clock_14,
  #tr_clock_6 .td_clock_15,
  #tr_clock_6 .td_clock_16,
  #tr_clock_6 .td_clock_17,
  #tr_clock_6 .td_clock_18,
  #tr_clock_6 .td_clock_19,
  #tr_clock_6 .td_clock_20,
  #tr_clock_6 .td_clock_21,
  #tr_clock_6 .td_clock_22,
  #tr_clock_6 .td_clock_23,
  #tr_clock_7 .td_clock_10,
  #tr_clock_7 .td_clock_11,
  #tr_clock_7 .td_clock_12,
  #tr_clock_7 .td_clock_13,
  #tr_clock_7 .td_clock_14,
  #tr_clock_7 .td_clock_15,
  #tr_clock_7 .td_clock_16,
  #tr_clock_7 .td_clock_17,
  #tr_clock_7 .td_clock_18,
  #tr_clock_7 .td_clock_19,
  #tr_clock_7 .td_clock_20,
  #tr_clock_7 .td_clock_21,
  #tr_clock_7 .td_clock_22,
  #tr_clock_7 .td_clock_23,
  #tr_clock_8 .td_clock_8,
  #tr_clock_8 .td_clock_9,
  #tr_clock_8 .td_clock_23,
  #tr_clock_8 .td_clock_24,
  #tr_clock_9 .td_clock_8,
  #tr_clock_9 .td_clock_9,
  #tr_clock_9 .td_clock_23,
  #tr_clock_9 .td_clock_24,
  #tr_clock_10 .td_clock_7,
  #tr_clock_10 .td_clock_25,
  #tr_clock_10 .td_clock_26,
  #tr_clock_11 .td_clock_7,
  #tr_clock_11 .td_clock_25,
  #tr_clock_11 .td_clock_26,
  #tr_clock_12 .td_clock_7,
  #tr_clock_12 .td_clock_25,
  #tr_clock_12 .td_clock_26,
  #tr_clock_13 .td_clock_7,
  #tr_clock_13 .td_clock_25,
  #tr_clock_13 .td_clock_26,
  #tr_clock_14 .td_clock_7,
  #tr_clock_14 .td_clock_25,
  #tr_clock_14 .td_clock_26,
  #tr_clock_15 .td_clock_7,
  #tr_clock_15 .td_clock_25,
  #tr_clock_15 .td_clock_26,
  #tr_clock_16 .td_clock_7,
  #tr_clock_16 .td_clock_25,
  #tr_clock_16 .td_clock_26,
  #tr_clock_17 .td_clock_7,
  #tr_clock_17 .td_clock_25,
  #tr_clock_17 .td_clock_26,
  #tr_clock_18 .td_clock_7,
  #tr_clock_18 .td_clock_25,
  #tr_clock_18 .td_clock_26,
  #tr_clock_19 .td_clock_7,
  #tr_clock_19 .td_clock_25,
  #tr_clock_19 .td_clock_26,
  #tr_clock_20 .td_clock_7,
  #tr_clock_20 .td_clock_25,
  #tr_clock_20 .td_clock_26,
  #tr_clock_21 .td_clock_7,
  #tr_clock_21 .td_clock_25,
  #tr_clock_21 .td_clock_26,
  #tr_clock_22 .td_clock_7,
  #tr_clock_22 .td_clock_25,
  #tr_clock_22 .td_clock_26,
  #tr_clock_23 .td_clock_7,
  #tr_clock_23 .td_clock_25,
  #tr_clock_23 .td_clock_26,
  #tr_clock_24 .td_clock_8,
  #tr_clock_24 .td_clock_9,
  #tr_clock_24 .td_clock_24,
  #tr_clock_24 .td_clock_25,
  #tr_clock_25 .td_clock_10,
  #tr_clock_25 .td_clock_11,
  #tr_clock_25 .td_clock_12,
  #tr_clock_25 .td_clock_13,
  #tr_clock_25 .td_clock_14,
  #tr_clock_25 .td_clock_15,
  #tr_clock_25 .td_clock_16,
  #tr_clock_25 .td_clock_17,
  #tr_clock_25 .td_clock_18,
  #tr_clock_25 .td_clock_19,
  #tr_clock_25 .td_clock_20,
  #tr_clock_25 .td_clock_21,
  #tr_clock_25 .td_clock_22,
  #tr_clock_25 .td_clock_23,
  #tr_clock_26 .td_clock_10,
  #tr_clock_26 .td_clock_11,
  #tr_clock_26 .td_clock_12,
  #tr_clock_26 .td_clock_13,
  #tr_clock_26 .td_clock_14,
  #tr_clock_26 .td_clock_15,
  #tr_clock_26 .td_clock_16,
  #tr_clock_26 .td_clock_17,
  #tr_clock_26 .td_clock_18,
  #tr_clock_26 .td_clock_19,
  #tr_clock_26 .td_clock_20,
  #tr_clock_26 .td_clock_21,
  #tr_clock_26 .td_clock_22,
  #tr_clock_26 .td_clock_23`
)

// 水管
const pipe_color = document.querySelectorAll(
	`#tr_pipe_2 .td_pipe_1,
  #tr_pipe_2 .td_pipe_3,
  #tr_pipe_2 .td_pipe_8,
  #tr_pipe_2 .td_pipe_9,
  #tr_pipe_2 .td_pipe_10,
  #tr_pipe_2 .td_pipe_11,
  #tr_pipe_2 .td_pipe_12,
  #tr_pipe_2 .td_pipe_13,
  #tr_pipe_2 .td_pipe_14,
  #tr_pipe_3 .td_pipe_1,
  #tr_pipe_3 .td_pipe_3,
  #tr_pipe_3 .td_pipe_8,
  #tr_pipe_3 .td_pipe_9,
  #tr_pipe_3 .td_pipe_10,
  #tr_pipe_3 .td_pipe_11,
  #tr_pipe_3 .td_pipe_12,
  #tr_pipe_3 .td_pipe_13,
  #tr_pipe_3 .td_pipe_14,
  #tr_pipe_4 .td_pipe_1,
  #tr_pipe_4 .td_pipe_3,
  #tr_pipe_4 .td_pipe_8,
  #tr_pipe_4 .td_pipe_9,
  #tr_pipe_4 .td_pipe_10,
  #tr_pipe_4 .td_pipe_11,
  #tr_pipe_4 .td_pipe_12,
  #tr_pipe_4 .td_pipe_13,
  #tr_pipe_4 .td_pipe_14,
  #tr_pipe_5 .td_pipe_1,
  #tr_pipe_5 .td_pipe_3,
  #tr_pipe_5 .td_pipe_8,
  #tr_pipe_5 .td_pipe_9,
  #tr_pipe_5 .td_pipe_10,
  #tr_pipe_5 .td_pipe_11,
  #tr_pipe_5 .td_pipe_12,
  #tr_pipe_5 .td_pipe_13,
  #tr_pipe_5 .td_pipe_14,
  #tr_pipe_6 .td_pipe_1,
  #tr_pipe_6 .td_pipe_3,
  #tr_pipe_6 .td_pipe_8,
  #tr_pipe_6 .td_pipe_9,
  #tr_pipe_6 .td_pipe_10,
  #tr_pipe_6 .td_pipe_11,
  #tr_pipe_6 .td_pipe_12,
  #tr_pipe_6 .td_pipe_13,
  #tr_pipe_6 .td_pipe_14,
  #tr_pipe_8 .td_pipe_2,
  #tr_pipe_8 .td_pipe_3,
  #tr_pipe_8 .td_pipe_4,
  #tr_pipe_8 .td_pipe_5,
  #tr_pipe_8 .td_pipe_6,
  #tr_pipe_8 .td_pipe_7,
  #tr_pipe_8 .td_pipe_8,
  #tr_pipe_8 .td_pipe_9,
  #tr_pipe_8 .td_pipe_10,
  #tr_pipe_8 .td_pipe_11,
  #tr_pipe_8 .td_pipe_12,
  #tr_pipe_8 .td_pipe_13,
  #tr_pipe_9 .td_pipe_2,
  #tr_pipe_9 .td_pipe_3,
  #tr_pipe_9 .td_pipe_4,
  #tr_pipe_9 .td_pipe_5,
  #tr_pipe_9 .td_pipe_6,
  #tr_pipe_9 .td_pipe_7,
  #tr_pipe_9 .td_pipe_8,
  #tr_pipe_9 .td_pipe_9,
  #tr_pipe_9 .td_pipe_10,
  #tr_pipe_9 .td_pipe_11,
  #tr_pipe_9 .td_pipe_12,
  #tr_pipe_9 .td_pipe_13,
  #tr_pipe_1 .td_pipe_1,
#tr_pipe_1 .td_pipe_2,
#tr_pipe_1 .td_pipe_3,
#tr_pipe_1 .td_pipe_4,
#tr_pipe_1 .td_pipe_5,
#tr_pipe_1 .td_pipe_6,
#tr_pipe_1 .td_pipe_7,
#tr_pipe_1 .td_pipe_8,
#tr_pipe_1 .td_pipe_9,
#tr_pipe_1 .td_pipe_10,
#tr_pipe_1 .td_pipe_11,
#tr_pipe_1 .td_pipe_12,
#tr_pipe_1 .td_pipe_13,
#tr_pipe_1 .td_pipe_14,
#tr_pipe_2 .td_pipe_1,
#tr_pipe_2 .td_pipe_14,
#tr_pipe_3 .td_pipe_1,
#tr_pipe_3 .td_pipe_14,
#tr_pipe_4 .td_pipe_1,
#tr_pipe_4 .td_pipe_14,
#tr_pipe_5 .td_pipe_1,
#tr_pipe_5 .td_pipe_14,
#tr_pipe_6 .td_pipe_1,
#tr_pipe_6 .td_pipe_14,
#tr_pipe_7 .td_pipe_1,
#tr_pipe_7 .td_pipe_2,
#tr_pipe_7 .td_pipe_3,
#tr_pipe_7 .td_pipe_4,
#tr_pipe_7 .td_pipe_5,
#tr_pipe_7 .td_pipe_6,
#tr_pipe_7 .td_pipe_7,
#tr_pipe_7 .td_pipe_8,
#tr_pipe_7 .td_pipe_9,
#tr_pipe_7 .td_pipe_10,
#tr_pipe_7 .td_pipe_11,
#tr_pipe_7 .td_pipe_12,
#tr_pipe_7 .td_pipe_13,
#tr_pipe_7 .td_pipe_14,
#tr_pipe_8 .td_pipe_2,
#tr_pipe_8 .td_pipe_13,
#tr_pipe_9 .td_pipe_2,
#tr_pipe_9 .td_pipe_13,
#tr_pipe_2 .td_pipe_2,
#tr_pipe_2 .td_pipe_4,
#tr_pipe_2 .td_pipe_5,
#tr_pipe_2 .td_pipe_6,
#tr_pipe_2 .td_pipe_7,
#tr_pipe_2 .td_pipe_13,
#tr_pipe_3 .td_pipe_2,
#tr_pipe_3 .td_pipe_4,
#tr_pipe_3 .td_pipe_5,
#tr_pipe_3 .td_pipe_6,
#tr_pipe_3 .td_pipe_7,
#tr_pipe_3 .td_pipe_13,
#tr_pipe_4 .td_pipe_2,
#tr_pipe_4 .td_pipe_4,
#tr_pipe_4 .td_pipe_5,
#tr_pipe_4 .td_pipe_6,
#tr_pipe_4 .td_pipe_7,
#tr_pipe_4 .td_pipe_13,
#tr_pipe_5 .td_pipe_2,
#tr_pipe_5 .td_pipe_4,
#tr_pipe_5 .td_pipe_5,
#tr_pipe_5 .td_pipe_6,
#tr_pipe_5 .td_pipe_7,
#tr_pipe_5 .td_pipe_13,
#tr_pipe_6 .td_pipe_2,
#tr_pipe_6 .td_pipe_4,
#tr_pipe_6 .td_pipe_5,
#tr_pipe_6 .td_pipe_6,
#tr_pipe_6 .td_pipe_7,
#tr_pipe_6 .td_pipe_13,
#tr_pipe_8 .td_pipe_3,
#tr_pipe_8 .td_pipe_5,
#tr_pipe_8 .td_pipe_6,
#tr_pipe_8 .td_pipe_7,
#tr_pipe_8 .td_pipe_12,
#tr_pipe_9 .td_pipe_3,
#tr_pipe_9 .td_pipe_5,
#tr_pipe_9 .td_pipe_6,
#tr_pipe_9 .td_pipe_7,
#tr_pipe_9 .td_pipe_12
  `
)

// 馬力歐
const mario_color = document.querySelectorAll(
	`#tr_mario_1 .td_mario_4,
  #tr_mario_1 .td_mario_5,
  #tr_mario_1 .td_mario_6,
  #tr_mario_1 .td_mario_7,
  #tr_mario_1 .td_mario_8,
  #tr_mario_1 .td_mario_9,
  #tr_mario_2 .td_mario_3,
  #tr_mario_2 .td_mario_4,
  #tr_mario_2 .td_mario_5,
  #tr_mario_2 .td_mario_6,
  #tr_mario_2 .td_mario_7,
  #tr_mario_2 .td_mario_8,
  #tr_mario_2 .td_mario_9,
  #tr_mario_2 .td_mario_10,
  #tr_mario_2 .td_mario_11,
  #tr_mario_2 .td_mario_12,
  #tr_mario_2 .td_mario_13,
  #tr_mario_8 .td_mario_6,
  #tr_mario_9 .td_mario_6,
  #tr_mario_9 .td_mario_9,
  #tr_mario_10 .td_mario_6,
  #tr_mario_10 .td_mario_7,
  #tr_mario_10 .td_mario_8,
  #tr_mario_10 .td_mario_9,
  #tr_mario_11 .td_mario_5,
  #tr_mario_11 .td_mario_7,
  #tr_mario_11 .td_mario_8,
  #tr_mario_11 .td_mario_10,
  #tr_mario_12 .td_mario_5,
  #tr_mario_12 .td_mario_6,
  #tr_mario_12 .td_mario_7,
  #tr_mario_12 .td_mario_8,
  #tr_mario_12 .td_mario_9,
  #tr_mario_12 .td_mario_10,
  #tr_mario_13 .td_mario_3,
  #tr_mario_13 .td_mario_4,
  #tr_mario_13 .td_mario_5,
  #tr_mario_13 .td_mario_6,
  #tr_mario_13 .td_mario_7,
  #tr_mario_13 .td_mario_8,
  #tr_mario_13 .td_mario_9,
  #tr_mario_13 .td_mario_10,
  #tr_mario_13 .td_mario_11,
  #tr_mario_13 .td_mario_12,
  #tr_mario_14 .td_mario_3,
  #tr_mario_14 .td_mario_4,
  #tr_mario_14 .td_mario_5,
  #tr_mario_14 .td_mario_6,
  #tr_mario_14 .td_mario_9,
  #tr_mario_14 .td_mario_10,
  #tr_mario_14 .td_mario_11,
  #tr_mario_14 .td_mario_12,
  #tr_mario_3 .td_mario_3,
#tr_mario_3 .td_mario_4,
#tr_mario_3 .td_mario_5,
#tr_mario_3 .td_mario_6,
#tr_mario_3 .td_mario_9,
#tr_mario_4 .td_mario_2,
#tr_mario_4 .td_mario_4,
#tr_mario_4 .td_mario_5,
#tr_mario_4 .td_mario_9,
#tr_mario_5 .td_mario_2,
#tr_mario_5 .td_mario_4,
#tr_mario_5 .td_mario_5,
#tr_mario_5 .td_mario_6,
#tr_mario_5 .td_mario_10,
#tr_mario_6 .td_mario_2,
#tr_mario_6 .td_mario_3,
#tr_mario_6 .td_mario_4,
#tr_mario_6 .td_mario_9,
#tr_mario_6 .td_mario_10,
#tr_mario_6 .td_mario_11,
#tr_mario_6 .td_mario_12,
#tr_mario_6 .td_mario_13,
#tr_mario_8 .td_mario_3,
#tr_mario_8 .td_mario_4,
#tr_mario_8 .td_mario_5,
#tr_mario_8 .td_mario_7,
#tr_mario_8 .td_mario_8,
#tr_mario_8 .td_mario_9,
#tr_mario_9 .td_mario_2,
#tr_mario_9 .td_mario_3,
#tr_mario_9 .td_mario_4,
#tr_mario_9 .td_mario_5,
#tr_mario_9 .td_mario_7,
#tr_mario_9 .td_mario_8,
#tr_mario_9 .td_mario_10,
#tr_mario_9 .td_mario_11,
#tr_mario_9 .td_mario_12,
#tr_mario_9 .td_mario_13,
#tr_mario_10 .td_mario_1,
#tr_mario_10 .td_mario_2,
#tr_mario_10 .td_mario_3,
#tr_mario_10 .td_mario_4,
#tr_mario_10 .td_mario_5,
#tr_mario_10 .td_mario_10,
#tr_mario_10 .td_mario_11,
#tr_mario_10 .td_mario_12,
#tr_mario_10 .td_mario_13,
#tr_mario_10 .td_mario_14,
#tr_mario_11 .td_mario_3,
#tr_mario_11 .td_mario_4,
#tr_mario_11 .td_mario_11,
#tr_mario_11 .td_mario_12,
#tr_mario_15 .td_mario_2,
#tr_mario_15 .td_mario_3,
#tr_mario_15 .td_mario_4,
#tr_mario_15 .td_mario_5,
#tr_mario_15 .td_mario_10,
#tr_mario_15 .td_mario_11,
#tr_mario_15 .td_mario_12,
#tr_mario_15 .td_mario_13,
#tr_mario_16 .td_mario_1,
#tr_mario_16 .td_mario_2,
#tr_mario_16 .td_mario_3,
#tr_mario_16 .td_mario_4,
#tr_mario_16 .td_mario_5,
#tr_mario_16 .td_mario_10,
#tr_mario_16 .td_mario_11,
#tr_mario_16 .td_mario_12,
#tr_mario_16 .td_mario_13,
#tr_mario_16 .td_mario_14,
#tr_mario_3 .td_mario_7,
#tr_mario_3 .td_mario_8,
#tr_mario_3 .td_mario_10,
#tr_mario_4 .td_mario_3,
#tr_mario_4 .td_mario_6,
#tr_mario_4 .td_mario_7,
#tr_mario_4 .td_mario_8,
#tr_mario_4 .td_mario_10,
#tr_mario_4 .td_mario_11,
#tr_mario_4 .td_mario_12,
#tr_mario_4 .td_mario_13,
#tr_mario_5 .td_mario_3,
#tr_mario_5 .td_mario_7,
#tr_mario_5 .td_mario_8,
#tr_mario_5 .td_mario_9,
#tr_mario_5 .td_mario_11,
#tr_mario_5 .td_mario_12,
#tr_mario_5 .td_mario_13,
#tr_mario_5 .td_mario_14,
#tr_mario_6 .td_mario_5,
#tr_mario_6 .td_mario_6,
#tr_mario_6 .td_mario_7,
#tr_mario_6 .td_mario_8,
#tr_mario_7 .td_mario_4,
#tr_mario_7 .td_mario_5,
#tr_mario_7 .td_mario_6,
#tr_mario_7 .td_mario_7,
#tr_mario_7 .td_mario_8,
#tr_mario_7 .td_mario_9,
#tr_mario_7 .td_mario_10,
#tr_mario_7 .td_mario_11,
#tr_mario_7 .td_mario_12,
#tr_mario_11 .td_mario_1,
#tr_mario_11 .td_mario_2,
#tr_mario_11 .td_mario_6,
#tr_mario_11 .td_mario_9,
#tr_mario_11 .td_mario_13,
#tr_mario_11 .td_mario_14,
#tr_mario_12 .td_mario_1,
#tr_mario_12 .td_mario_2,
#tr_mario_12 .td_mario_3,
#tr_mario_12 .td_mario_4,
#tr_mario_12 .td_mario_11,
#tr_mario_12 .td_mario_12,
#tr_mario_12 .td_mario_13,
#tr_mario_12 .td_mario_14,
#tr_mario_13 .td_mario_1,
#tr_mario_13 .td_mario_2,
#tr_mario_13 .td_mario_13,
#tr_mario_13 .td_mario_14
  `
)

// 壞香菇(還未用)

if (bad_mushroom_R.style.display === 'block') {
	const bad_mushroom_R_color = document.querySelectorAll(`
  #tr_bad_mushroom_R_1 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_1 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_2 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_3 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_1,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_12,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_1,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_8 .td_bad_mushroom_12,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_2,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_9 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_4 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_5 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_6,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_7,
  #tr_bad_mushroom_R_6 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_10 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_3,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_11 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_4,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_8,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_9,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_10,
  #tr_bad_mushroom_R_12 .td_bad_mushroom_11,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_5,
  #tr_bad_mushroom_R_7 .td_bad_mushroom_8,
  `)
}
if (bad_mushroom_L.style.display === 'block') {
	const bad_mushroom_R_color = document.querySelectorAll(
		`#tr_bad_mushroom_L_1 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_1 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_2 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_3 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_4 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_5 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_6 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_1,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_7 .td_bad_mushroom_12,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_1,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_4,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_5,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_6,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_7,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_8,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_9,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_8 .td_bad_mushroom_12,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_2,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_3,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_10,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_11,
    #tr_bad_mushroom_L_9 .td_bad_mushroom_4,
#tr_bad_mushroom_L_9 .td_bad_mushroom_5,
#tr_bad_mushroom_L_9 .td_bad_mushroom_6,
#tr_bad_mushroom_L_9 .td_bad_mushroom_7,
#tr_bad_mushroom_L_9 .td_bad_mushroom_8,
#tr_bad_mushroom_L_9 .td_bad_mushroom_9,
#tr_bad_mushroom_L_10 .td_bad_mushroom_4,
#tr_bad_mushroom_L_10 .td_bad_mushroom_5,
#tr_bad_mushroom_L_10 .td_bad_mushroom_6,
#tr_bad_mushroom_L_10 .td_bad_mushroom_7,
#tr_bad_mushroom_L_10 .td_bad_mushroom_8,
#tr_bad_mushroom_L_10 .td_bad_mushroom_9,
#tr_bad_mushroom_L_11 .td_bad_mushroom_6,
#tr_bad_mushroom_L_11 .td_bad_mushroom_7,
#tr_bad_mushroom_L_11 .td_bad_mushroom_8,
#tr_bad_mushroom_L_12 .td_bad_mushroom_6,
#tr_bad_mushroom_L_12 .td_bad_mushroom_7,
#tr_bad_mushroom_L_4 .td_bad_mushroom_3,
#tr_bad_mushroom_L_4 .td_bad_mushroom_4,
#tr_bad_mushroom_L_4 .td_bad_mushroom_9,
#tr_bad_mushroom_L_4 .td_bad_mushroom_10,
#tr_bad_mushroom_L_5 .td_bad_mushroom_5,
#tr_bad_mushroom_L_5 .td_bad_mushroom_8,
#tr_bad_mushroom_L_6 .td_bad_mushroom_5,
#tr_bad_mushroom_L_6 .td_bad_mushroom_6,
#tr_bad_mushroom_L_6 .td_bad_mushroom_7,
#tr_bad_mushroom_L_6 .td_bad_mushroom_8,
#tr_bad_mushroom_L_10 .td_bad_mushroom_3,
#tr_bad_mushroom_L_11 .td_bad_mushroom_2,
#tr_bad_mushroom_L_11 .td_bad_mushroom_3,
#tr_bad_mushroom_L_11 .td_bad_mushroom_4,
#tr_bad_mushroom_L_11 .td_bad_mushroom_5,
#tr_bad_mushroom_L_11 .td_bad_mushroom_9,
#tr_bad_mushroom_L_11 .td_bad_mushroom_10,
#tr_bad_mushroom_L_12 .td_bad_mushroom_2,
#tr_bad_mushroom_L_12 .td_bad_mushroom_3,
#tr_bad_mushroom_L_12 .td_bad_mushroom_4,
#tr_bad_mushroom_L_12 .td_bad_mushroom_5,
#tr_bad_mushroom_L_12 .td_bad_mushroom_8,
#tr_bad_mushroom_L_12 .td_bad_mushroom_9,
#tr_bad_mushroom_L_5 .td_bad_mushroom_4,
#tr_bad_mushroom_L_5 .td_bad_mushroom_9,
#tr_bad_mushroom_L_6 .td_bad_mushroom_4,
#tr_bad_mushroom_L_6 .td_bad_mushroom_9,
#tr_bad_mushroom_L_7 .td_bad_mushroom_4,
#tr_bad_mushroom_L_7 .td_bad_mushroom_5,
#tr_bad_mushroom_L_7 .td_bad_mushroom_8,
#tr_bad_mushroom_L_7 .td_bad_mushroom_9
    `
	)
}

// 數字
const number_color = document.querySelectorAll(
	`.tr_colon_2 .td_colon_1,
  .tr_colon_4 .td_colon_1,
  .tr_zero_1 .td_zero_2,
  .tr_zero_1 .td_zero_3,
  .tr_zero_2 .td_zero_1,
  .tr_zero_2 .td_zero_4,
  .tr_zero_3 .td_zero_1,
  .tr_zero_3 .td_zero_4,
  .tr_zero_4 .td_zero_1,
  .tr_zero_4 .td_zero_4,
  .tr_zero_5 .td_zero_2,
  .tr_zero_5 .td_zero_3,
  .tr_one_1 .td_one_2,
.tr_one_1 .td_one_3,
.tr_one_2 .td_one_1,
.tr_one_2 .td_one_3,
.tr_one_3 .td_one_3,
.tr_one_4 .td_one_3,
.tr_one_5 .td_one_1,
.tr_one_5 .td_one_2,
.tr_one_5 .td_one_3,
.tr_one_5 .td_one_4,
.tr_two_1 .td_two_1,
.tr_two_1 .td_two_2,
.tr_two_1 .td_two_3,
.tr_two_1 .td_two_4,
.tr_two_2 .td_two_4,
.tr_two_3 .td_two_3,
.tr_two_4 .td_two_2,
.tr_two_5 .td_two_1,
.tr_two_5 .td_two_2,
.tr_two_5 .td_two_3,
.tr_two_5 .td_two_4,
.tr_three_1 .td_three_1,
.tr_three_1 .td_three_2,
.tr_three_1 .td_three_3,
.tr_three_1 .td_three_4,
.tr_three_2 .td_three_4,
.tr_three_3 .td_three_1,
.tr_three_3 .td_three_2,
.tr_three_3 .td_three_3,
.tr_three_3 .td_three_4,
.tr_three_4 .td_three_4,
.tr_three_5 .td_three_1,
.tr_three_5 .td_three_2,
.tr_three_5 .td_three_3,
.tr_three_5 .td_three_4,
.tr_four_1 .td_four_2,
.tr_four_1 .td_four_3,
.tr_four_2 .td_four_1,
.tr_four_2 .td_four_3,
.tr_four_3 .td_four_1,
.tr_four_3 .td_four_3,
.tr_four_4 .td_four_1,
.tr_four_4 .td_four_2,
.tr_four_4 .td_four_3,
.tr_four_4 .td_four_4,
.tr_four_5 .td_four_3,
.tr_five_1 .td_five_1,
.tr_five_1 .td_five_2,
.tr_five_1 .td_five_3,
.tr_five_1 .td_five_4,
.tr_five_2 .td_five_1,
.tr_five_3 .td_five_1,
.tr_five_3 .td_five_2,
.tr_five_3 .td_five_3,
.tr_five_3 .td_five_4,
.tr_five_4 .td_five_4,
.tr_five_5 .td_five_1,
.tr_five_5 .td_five_2,
.tr_five_5 .td_five_3,
.tr_five_5 .td_five_4,
.tr_six_1 .td_six_1,
.tr_six_1 .td_six_2,
.tr_six_1 .td_six_3,
.tr_six_1 .td_six_4,
.tr_six_2 .td_six_1,
.tr_six_3 .td_six_1,
.tr_six_3 .td_six_2,
.tr_six_3 .td_six_3,
.tr_six_3 .td_six_4,
.tr_six_4 .td_six_1,
.tr_six_4 .td_six_4,
.tr_six_5 .td_six_1,
.tr_six_5 .td_six_2,
.tr_six_5 .td_six_3,
.tr_six_5 .td_six_4,
.tr_seven_1 .td_seven_1,
.tr_seven_1 .td_seven_2,
.tr_seven_1 .td_seven_3,
.tr_seven_1 .td_seven_4,
.tr_seven_2 .td_seven_4,
.tr_seven_3 .td_seven_3,
.tr_seven_4 .td_seven_2,
.tr_seven_5 .td_seven_2,
.tr_eight_1 .td_eight_1,
.tr_eight_1 .td_eight_2,
.tr_eight_1 .td_eight_3,
.tr_eight_1 .td_eight_4,
.tr_eight_2 .td_eight_1,
.tr_eight_2 .td_eight_4,
.tr_eight_3 .td_eight_1,
.tr_eight_3 .td_eight_2,
.tr_eight_3 .td_eight_3,
.tr_eight_3 .td_eight_4,
.tr_eight_4 .td_eight_1,
.tr_eight_4 .td_eight_4,
.tr_eight_5 .td_eight_1,
.tr_eight_5 .td_eight_2,
.tr_eight_5 .td_eight_3,
.tr_eight_5 .td_eight_4,
.tr_nine_1 .td_nine_1,
.tr_nine_1 .td_nine_2,
.tr_nine_1 .td_nine_3,
.tr_nine_1 .td_nine_4,
.tr_nine_2 .td_nine_1,
.tr_nine_2 .td_nine_4,
.tr_nine_3 .td_nine_1,
.tr_nine_3 .td_nine_2,
.tr_nine_3 .td_nine_3,
.tr_nine_3 .td_nine_4,
.tr_nine_4 .td_nine_4,
.tr_nine_5 .td_nine_1,
.tr_nine_5 .td_nine_2,
.tr_nine_5 .td_nine_3,
.tr_nine_5 .td_nine_4

`
)

// 天上石頭
const upStone_color = document.querySelectorAll(`
.td_upStone
`)

// 天上石頭-L
const upSton_color_L = document.querySelectorAll(`
#tr_upStone_1 .td_upStone_1,
#tr_upStone_2 .td_upStone_1,
#tr_upStone_3 .td_upStone_1,
#tr_upStone_3 .td_upStone_3,
#tr_upStone_4 .td_upStone_1,
#tr_upStone_5 .td_upStone_1,
#tr_upStone_6 .td_upStone_1,
#tr_upStone_6 .td_upStone_3,
#tr_upStone_7 .td_upStone_1,
#tr_upStone_7 .td_upStone_3`)
// 天上石頭-R
// 天上石頭-B
// 天上石頭-T

// 地上石頭
const downStone_color = document.querySelectorAll(`
.td_stone
`)

const background_change = () => {
	const date = new Date()
	const min = date.getMinutes()
	const background_min = Math.floor(min / 10)
	console.log(background_min)

	if (background_min === 1) {
		for (const el of background_color) {
			el.style.background = '#000'
			el.style.border = '0.05px solid rgb(46, 46, 46)'
		}

		for (const el2 of clock_side) {
			el2.style.border = '0.05px solid rgb(100, 100, 100)'
		}

		for (const el3 of clock_red) {
			el3.style.border = '0.05px solid rgb(100, 100, 100)'
		}

		for (const el4 of clock_yellow) {
			el4.style.border = '0.05px solid rgb(100, 100, 100)'
		}

		for (const el5 of clock_green) {
			el5.style.border = '0.05px solid rgb(100, 100, 100)'
		}

		for (const el6 of pipe_color) {
			el6.style.border = '0.05px solid rgb(100, 100, 100)'
		}

		for (const el7 of mario_color) {
			el7.style.border = '0.05px solid rgb(150, 150, 150)'
		}

		for (const el8 of number_color) {
			el8.style.border = '0.05px solid rgb(46, 46, 46)'
			el8.style.background = '#fff'
		}

		// 天上石頭框框不能變色...
		// for (const el9 of upStone_color) {
		// 	el9.style.border = '0.05px solid rgb(46, 46, 46)'
		// }

		// for (const el10 of upSton_color_L) {
		// 	el10.style.border_left = '6px solid #000;'
		// }

		// 壞香菇無法換色

		body.style.background = 'rgb(46, 46, 46)'

		console.log(body)
	} else {
		for (const el of background_color) {
			el.style.background = 'rgb(255, 238, 208)'
			el.style.border = '0.05px solid rgb(218, 218, 218)'
		}

		for (const el2 of clock_side) {
			el2.style.border = '0.05px solid  rgb(218, 218, 218)'
		}

		for (const el3 of clock_red) {
			el3.style.border = '0.05px solid  rgb(218, 218, 218)'
		}

		for (const el4 of clock_yellow) {
			el4.style.border = '0.05px solid  rgb(218, 218, 218)'
		}

		for (const el5 of clock_green) {
			el5.style.border = '0.05px solid  rgb(218, 218, 218)'
		}

		for (const el6 of pipe_color) {
			el6.style.border = '0.05px solid rgb(218, 218, 218)'
		}

		for (const el7 of mario_color) {
			el7.style.border = '0.05px solid rgb(218, 218, 218)'
		}

		for (const el8 of number_color) {
			el8.style.border = '0.05px solid rgb(218, 218, 218)'
			el8.style.background = '#000'
		}

		body.style.background = ' rgb(218, 218, 218)'
	}
}
background_change()
setInterval(background_change, 1000)

// const bad_mushroom_color = document.querySelectorAll(`
// #tr_bad_mushroom_R_1 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_1 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_2 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_2 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_2 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_2 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_3 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_2,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_2,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_1,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_2,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_7 .td_bad_mushroom_12,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_1,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_2,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_8 .td_bad_mushroom_12,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_2,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_9 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_7
// #tr_bad_mushroom_R_4 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_4 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_5 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_6,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_7,
// #tr_bad_mushroom_R_6 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_10 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_3,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_11 .td_bad_mushroom_11,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_4,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_5,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_8,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_9,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_10,
// #tr_bad_mushroom_R_12 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_1 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_1 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_2 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_2 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_2 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_2 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_3 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_1,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_7 .td_bad_mushroom_12,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_1,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_8 .td_bad_mushroom_12,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_11,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_9 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_4 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_5 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_6,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_7,
// #tr_bad_mushroom_L_6 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_10 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_9,
// #tr_bad_mushroom_L_11 .td_bad_mushroom_10,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_2,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_3,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_4,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_5,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_8,
// #tr_bad_mushroom_L_12 .td_bad_mushroom_9,
// `)
